# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4mud

include $(JUPITERROOT)/config/common.gmk

CPPFLAGS += -D__MUDREPLICA__
CPPFLAGS += -D__FRONTENDCAP__
