# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4vtx

CPPFLAGS += -D__HOSHINA__

include $(JUPITERROOT)/config/common.gmk

