#ifndef __J4VERSION_INFO__
#define __J4VERSION_INFO__

#define __J4VERSION_INFO_VERSION__ "2.04"
#define __J4VERSION_INFO_VERSION_SERIAL__ 204
#define __J4VERSION_INFO_VERSION_DATETIME__ "$Date$"

#define __J4VERSION_INFO_BUILD_HOST__ "host"
#define __J4VERSION_INFO_BUILD_DATETIME__ "20080327.000000"
#define __J4VERSION_INFO_BUILD_ACCOUNT__ "dummy"

#endif
