#ifndef __J4VERSION_INFO__
#define __J4VERSION_INFO__

#define __J4VERSION_INFO_VERSION__ "2.02"
#define __J4VERSION_INFO_VERSION_SERIAL__ 202
#define __J4VERSION_INFO_VERSION_DATETIME__ "$Date$"

#define __J4VERSION_INFO_BUILD_HOST__ "host"
#define __J4VERSION_INFO_BUILD_DATETIME__ "20070514.000000"
#define __J4VERSION_INFO_BUILD_ACCOUNT__ "dummy"

#endif
