# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4bd
	     
CPPFLAGS  += -I../ir/include

include $(JUPITERROOT)/config/common.gmk

