# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4ir
	     
CPPFLAGS += -I$(JUPITERROOT)/sources/sol/include

include $(JUPITERROOT)/config/common.gmk

