# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4clx

include $(JUPITERROOT)/config/common.gmk

CPPFLAGS += -D__REPLICA__
#CPPFLAGS += -D__DRAWONETOWER__

CPPFLAGS += -I../tpc/include
