#!/bin/sh
for i in `find $JUPITERROOT/sources -name '*.hh'`; do
   fn=`basename $i`
   dn=`dirname $i`
   (cd $dn; $JUPITERROOT/scripts/mkansi.pl $fn; mv out/$fn .; rmdir out)
done
for i in `find $JUPITERROOT/sources -name '*.cc'`; do
   fn=`basename $i`
   dn=`dirname $i`
   (cd $dn; $JUPITERROOT/scripts/mkansi.pl $fn; mv out/$fn .; rmdir out)
done

exit 0
