# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4sol

CPPFLAGS += -I$(G4BASE)/visualization/management/include
CPPFLAGS += -I$(G4BASE)/visualization/modeling/include

include $(JUPITERROOT)/config/common.gmk

