# $Id$
# --------------------------------------------------------------
#   GNUmakefile for examples module.
#                             .G4UserGroup, 2000
# --------------------------------------------------------------

name     := J4kern

include $(G4INSTALL)/config/G4UI_USE.gmk
include $(G4INSTALL)/config/G4VIS_USE.gmk
include $(G4INSTALL)/config/interactivity.gmk
include $(G4INSTALL)/config/analysis.gmk

include $(JUPITERROOT)/config/common.gmk
include $(JUPITERROOT)/config/G4version.gmk

